server:
  port: 8080

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/cloudlogs_dev?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: weaponlin
#    url: jdbc:mysql://127.0.0.1:3306/cloudlogs_dev?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: weaponlin
#    driver-class-name: com.mysql.jdbc.Driver

